CrudMVC/Controllers/TablaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CrudMVC.Models;
using CrudMVC.Models.ViewModels;
using System.Data.Entity;

namespace CrudMVC.Controllers
{
    public class CrudController : Controller
    {
        // GET: Tabla
        public ActionResult Index()
        {
            List<ListTablaViewModel> lst;

            using (CrudEntities1 db = new CrudEntities1())
            {
                lst = (from d in db.tabla
                       select new ListTablaViewModel
                       {
                           Id = d.Id,
                           Nombre = d.Nombre,
                           Correo = d.Correo,
                           Fecha_nacimiento = d.Fecha_nacimiento,

                       }).ToList();

            }

            return View(lst);
        }


        public ActionResult Nuevo()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Nuevo(TablaViewModel model)
        {
            try
            {
                if ( ModelState.IsValid)
                {
                    using (CrudEntities1 db = new CrudEntities1())
                    {
                        var oTabla = new tabla
                        {
                            Nombre = model.Nombre,
                            Correo = model.Correo,
                            Fecha_nacimiento = model.Fecha_nacimiento
                        };

                        db.tabla.Add(oTabla);
                        db.SaveChanges();
                    }
                    return Redirect("~/Crud/");
                    //return Redirect("/");

                }
                return View(model);
            }

            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }


        public ActionResult Editar(int Id)
        {
            TablaViewModel model = new TablaViewModel();
            using (CrudEntities1 db = new CrudEntities1())
            {
                var oTabla = db.tabla.Find(Id);
                model.Id = oTabla.Id;
                model.Nombre = oTabla.Nombre;
                model.Correo = oTabla.Correo;
                model.Fecha_nacimiento = oTabla.Fecha_nacimiento;
                model.Id = oTabla.Id;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(TablaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (CrudEntities1 db = new CrudEntities1())
                    {
                        var oTabla = db.tabla.Find(model.Id);
                        oTabla.Nombre = model.Nombre;
                        oTabla.Correo = model.Correo;
                        oTabla.Fecha_nacimiento = model.Fecha_nacimiento;

                        //db.Entry(oTabla).State = System.Data.Entity.EntityState.Modified;
                        db.Entry(oTabla).State = EntityState.Modified;
                        db.SaveChanges();
                    }

                    return Redirect("~/Crud/");

                }
                return View(model);
            }

            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int Id)
        {
            using (CrudEntities1 db = new CrudEntities1())
            {
                var oTabla = db.tabla.Find(Id);
                db.tabla.Remove(oTabla);
                //db.Entry(oTabla).State = EntityState.Deleted;
                db.SaveChanges();
            }
            return Redirect("~/Crud/");
        }

    }
}

CrudMVC/Views/Crud/Editar.cshtml
@model CrudMVC.Models.ViewModels.TablaViewModel

@{
    ViewBag.Title = "Nuevo";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Editar", "Crud", FormMethod.Post))
{

    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.Id)
            <div>
                @Html.LabelFor(d => d.Nombre)<br />
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })

            </div>
            <br />

            <div>
                @Html.LabelFor(d => d.Correo)<br />
                @Html.TextBoxFor(d => d.Correo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Correo, null, new { @class = "red" })
            </div>
            <br />

            <div>
                @Html.LabelFor(d => d.Fecha_nacimiento)<br />
                @Html.EditorFor(d => d.Fecha_nacimiento, "", new { @class = "form-control" })<br />
                @Html.ValidationMessageFor(d => d.Fecha_nacimiento, null, new { @class = "red" })

            </div>

            <br />
            <div style="text-align:right;">
                <input value="Guardar" class="btn-prim  ary" type="submit" />
            </div>
        </div>

    </div>
}

CrudMVC/Views/Crud/Index.cshtml
@model List<CrudMVC.Models.ViewModels.ListTablaViewModel>
@{
    ViewBag.Title = "Mis Datos";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="row" style="text-align:right; padding:5px;">
        <a href="~/Crud/Nuevo" class="btn btn-primary">Nuevo</a>
    </div>
        
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Correo</th>
                <th></th>
            </tr>
            @foreach (var oElemento in Model)
            {
            <tr>
                <td>@oElemento.Id</td>
                <td>@oElemento.Nombre</td>
                <td>@oElemento.Correo</td>
                <td>@oElemento.Fecha_nacimiento</td>
                <td>
                    <a class="btn btn-default" href="~/Crud/Editar/@oElemento.Id">Editar</a>
                    <a class="btn btn-danger" href="~/Crud/Eliminar/@oElemento.Id">Eliminar</a>

                </td>
            </tr>
            }

        </table>

    </div>
</div>

CrudMVC/Views/Crud/Nuevo.cshtml
@model CrudMVC.Models.ViewModels.TablaViewModel

@{
    ViewBag.Title = "Nuevo";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Nuevo","Crud",FormMethod.Post))
{

    <div class="row">
        <div class="col-md-12">
            <div>
                @Html.LabelFor(d => d.Nombre)<br />
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })

            </div>
            <br />

            <div>
                @Html.LabelFor(d => d.Correo)<br />
                @Html.TextBoxFor(d => d.Correo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Correo, null, new { @class = "red" })
            </div>
            <br />

            <div>
                @Html.LabelFor(d => d.Fecha_nacimiento)<br />
                @Html.EditorFor(d => d.Fecha_nacimiento, "", new { @class = "form-control" })<br />
                @Html.ValidationMessageFor(d => d.Fecha_nacimiento, null, new { @class = "red" })

            </div>

            <br />
            <div style="text-align:right;">
                <input value="Guardar" class="btn-primary" type="submit" />
            </div>
        </div>

    </div>
}